title: ham
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://LSH49769.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: dark # Or use dark

# Profile information
name: ham
tagline: A majestic array of natureâ€™s living wonders
about-description: i'm happy # Add Discription
pic: ape.webp # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: proshuto@gmail.com # Add your Email address
phone: 010 1234 5678 # Add your Phone number
website: www.youtube.com/watch?v=XtFI7SNtVpY # Add your website, do not add http://
# linkedin: # Add your Linkedin handle
github: HAMON_123 # Add your Github handle
twitter: 'ham' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
